//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testEFSqlServer4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Info
    {
        public int InfoId { get; set; }
        public int EmployeeId { get; set; }
        public int Age { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
