//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testEFSqlServer2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Metadata
    {
        public int Id { get; set; }
        public int Age { get; set; }
        public string Hobby { get; set; }
        public Nullable<System.DateTime> When { get; set; }
    }
}
